import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [name, setName] = useState('');
  const [list, setList] = useState([]);
  const [isEditing, setIsEditing] = useState(false);
  const [editID, setEditID] = useState(null);
  const [alert, setAlert] = useState({show: false, msg: '', type: ''});

  const handleSubmit = (e) => {
    e.preventDefault()
    if(!name){

    }else if(name && isEditing){

    }else{
      showAlert(true, 'item added to the list', 'success');
      const newItem = {id: new Date().getTime().toString(), title: name};
      setList([...list, newItem]);
      setName('');
      
    }
  }

  const showAlert = (show=false, msg='', type='') => {
    setAlert(show, msg, type);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Grocery Bud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className='section-center'>
        <form className='grocery-form' onSubmit={handleSubmit}>
          <h3>Grocery Bud</h3>
          <div className='form-control'>
            <input type="text" className='grocery' placeholder='e.g. eggs' value={name} onChange={(e) => setName(e.target.value)}  />
            <button type='submit' className='submit-btn'>
              {isEditing ? 'Edit' : 'Submit'}
            </button>
          </div>
        </form>
      </section>
    </div>
  )
}
