import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [name, setName] = useState('');
  const [list, setList] = useState([]);
  const [isEditing, setIsEditing] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault()
    console.log('hello');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Grocery Bud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className='section-center'>
        <form className='grocery-form' onSubmit={handleSubmit}>
          <h3>Grocery Bud</h3>
          <div className='form-control'>
            <input type="text" className='grocery' placeholder='e.g. eggs' value={name} onChange={(e) => setName(e.target.value)}  />
            <button type='submit' className='submit-btn'>
              {isEditing ? 'Edit' : 'Submit'}
            </button>
          </div>
        </form>
      </section>
    </div>
  )
}
